var objCharacters =
{
    "valen": {
        "name": "Valen",
        "liked": [
            "coffee",
            "cucumber",
            "cucumber_salad",
            "dandelion",
            "garlic",
            "green_tea",
            "herb_salad",
            "honey",
            "nettle",
            "pan_fried_salmon",
            "red_wine",
            "rose_hip",
            "rosehip_jam",
            "rosemary",
            "seaweed",
            "seaweed_salad",
            "spring_salad",
            "sweetroot",
            "underseaweed",
            "white_wine"
        ],
        "loved": [
            "beet",
            "beet_salad",
            "beet_soup",
            "deep_sea_soup",
            "dragon_scale",
            "harvest_plate",
            "rosemary_garlic_noodles",
            "summer_salad",
            "sushi_platter",
            "vegetable_soup"
        ]
    },
    "eiland": {
        "name": "Eiland",
        "liked": [
            "apple_pie",
            "berries_and_cream",
            "candied_lemon_peel",
            "candied_strawberries",
            "caramelized_moon_fruit",
            "caramel_candy",
            "cherry_cobbler",
            "cherry_tart",
            "chocolate",
            "crystal_berry_pie",
            "sour_lemon_cake",
            "lemon_pie",
            "peaches_and_cream",
            "pomegranate_sorbet",
            "pudding",
            "roasted_rice_tea",
            "strawberries_and_cream",
            "sweet_sesame_balls",
            "wildberry_pie",
            "wintergreen_ice_cream"
        ],
        "loved": [
            "caldosian_chocolate_cake",
            "coconut_cream_pie",
            "glowberry_cookies",
            "golden_cheesecake",
            "golden_cookies",
            "ice_cream_sundae",
            "mont_blanc",
            "pumpkin_pie",
            "spell_fruit_parfait",
            "strawberry_shortcake"
        ]
    },
    "maple": {
        "name": "Maple",
        "liked": [
            "blackberry",
            "blue_conch_shell",
            "cheese",
            "daisy",
            "glowberry_cookies",
            "golden_cookies",
            "grilled_cheese",
            "ice_cream_sundae",
            "jam_sandwich",
            "pink_scallop_shell",
            "pomegranate_sorbet",
            "pudding",
            "sand_dollar",
            "spirula_shell",
            "strawberry_shortcake",
            "sunflower",
            "trail_mix",
            "tulip",
            "wildberry_pie",
            "wintergreen_ice_cream"
        ],
        "loved": [
            "ancient_horn_circlet",
            "berries_and_cream",
            "chocolate",
            "hot_cocoa",
            "lemon_pie",
            "lost_crown_of_aldaria",
            "middlemist",
            "monarch_butterfly",
            "mont_blanc",
            "stone_shell"
        ]
    },
    "march": {
        "name": "March",
        "liked": [
            "beer",
            "chocolate",
            "caldosian_chocolate_cake",
            "coffee",
            "copper_ingot",
            "ore_copper",
            "ore_gold",
            "grilled_eel_rice_bowl",
            "hot_cocoa",
            "iron_ingot",
            "ore_iron",
            "ore_mistril",
            "mocha",
            "perch_risotto",
            "red_snapper_sushi",
            "sea_bream_rice",
            "sesame_tuna_bowl",
            "silver_ingot",
            "ore_silver",
            "spicy_crab_sushi"
        ],
        "loved": [
            "dragon_forged_bracelet",
            "gold_ingot",
            "meteorite",
            "mistril_ingot",
            "perfect_copper_ore",
            "perfect_gold_ore",
            "perfect_iron_ore",
            "perfect_mistril_ore",
            "perfect_silver_ore",
            "sushi_platter"
        ]
    },
    "vera": {
        "name": "Vera",
        "liked": [
            "beet_salad",
            "braised_burdock",
            "cauliflower_curry",
            "chickpea_curry",
            "coconut_milk",
            "cranberry_juice",
            "crispy_fried_earthshroom",
            "cucumber_salad",
            "orange_juice",
            "pomegranate",
            "pomegranate_juice",
            "roasted_cauliflower",
            "salted_watermelon",
            "sauteed_snow_peas",
            "seaweed_salad",
            "sesame_broccoli",
            "simmered_daikon",
            "steamed_broccoli",
            "tide_salad",
            "turnip_and_cabbage_salad"
        ],
        "loved": [
            "beet_soup",
            "chili_coconut_curry",
            "gazpacho",
            "harvest_plate",
            "mushroom_steak_dinner",
            "pomegranate_sorbet",
            "summer_salad",
            "sweet_potato_pie",
            "vegetable_pot_pie",
            "winter_stew"
        ]
    },
    "zorel": {
        "name": "Zorel",
        "liked": [
            "mushroom_rice",
            "red_toadstool",
            "upper_mines_mushroom",
            "glowing_mushroom",
            "miners_mushroom_stew",
            "wild_mushroom",
            "dandelion",
            "fiddlehead",
            "nettle",
            "wild_leek",
            "fennel",
            "sage"
        ],
        "loved": [
            "middlemist",
            "sunflower",
            "heather",
            "morel_mushroom"
        ],
        "spoiler": 1
    },
    "darcy": {
        "name": "Darcy",
        "liked": [
            "apple",
            "blackberry",
            "blueberry",
            "cherry",
            "coconut",
            "cranberry",
            "moon_fruit",
            "egg",
            "flour",
            "glowberry",
            "lemon",
            "orange",
            "peach",
            "pear",
            "pomegranate",
            "strawberry",
            "tea",
            "wild_berries",
            "wild_grapes",
            "wintergreen_berry"
        ],
        "loved": [
            "chocolate",
            "coconut_milk",
            "crystal_berries",
            "golden_cheesecake",
            "golden_cookies",
            "golden_egg",
            "golden_cow_milk",
            "cow_milk",
            "spell_fruit",
            "sugar"
        ]
    },
    "wheedle": {
        "name": "Wheedle",
        "liked": [
            "ore_diamond",
            "ore_emerald",
            "gold_ingot",
            "ore_gold",
            "golden_alpaca_wool",
            "golden_bristle",
            "golden_bull_horn",
            "golden_cheesecake",
            "golden_cookies",
            "golden_duck_egg",
            "golden_duck_feather",
            "golden_egg",
            "golden_feather",
            "golden_horse_hair",
            "golden_rabbit_wool",
            "golden_sheep_wool",
            "dragon_forged_bracelet",
            "ore_ruby",
            "rusted_treasure_chest",
            "ore_sapphire"
        ],
        "loved": [
            "ancient_gold_coin",
            "coin_lump",
            "fiber",
            "perfect_diamond",
            "perfect_emerald",
            "perfect_gold_ore",
            "perfect_pink_diamond",
            "perfect_ruby",
            "perfect_sapphire",
            "ore_pink_diamond"
        ]
    },
    "errol": {
        "name": "Errol",
        "liked": [
            "apple",
            "beer",
            "breaded_catfish",
            "canned_sardines",
            "ore_copper",
            "fish_stew",
            "ore_gold",
            "hot_toddy",
            "ore_iron",
            "ore_mistril",
            "latte",
            "mocha",
            "pear",
            "peat",
            "pomegranate",
            "red_wine",
            "ore_silver",
            "sweetroot",
            "upper_mines_mushroom",
            "wintergreen_ice_cream"
        ],
        "loved": [
            "baked_sweetroot",
            "braised_burdock",
            "clam_chowder",
            "fish_skewer",
            "miners_helmet",
            "miners_mushroom_stew",
            "pan_fried_bream",
            "perch_risotto",
            "shard_mass",
            "white_wine"
        ]
    },
    "balor": {
        "name": "Balor",
        "liked": [
            "cauliflower_curry",
            "chickpea_curry",
            "crystal_rose",
            "ore_diamond",
            "ore_emerald",
            "fog_orchid",
            "frost_lily",
            "gold_ingot",
            "ore_gold",
            "golden_cookies",
            "golden_cheesecake",
            "jasmine",
            "perfect_gold_ore",
            "ore_pink_diamond",
            "rose",
            "ore_ruby",
            "rusted_treasure_chest",
            "ore_sapphire",
            "sapphire_betta",
            "snowdrop_anemone"
        ],
        "loved": [
            "alda_gem_bracelet",
            "apple_honey_curry",
            "chili_coconut_curry",
            "deluxe_curry",
            "family_crest_pendant",
            "perfect_diamond",
            "perfect_emerald",
            "perfect_pink_diamond",
            "perfect_ruby",
            "perfect_sapphire"
        ]
    },
    "luc": {
        "name": "Luc",
        "liked": [
            "ant",
            "butterfly",
            "cave_shrimp",
            "cheese",
            "chocolate",
            "cricket",
            "fuzzy_moth",
            "hot_cocoa",
            "hummingbird_hawk_moth",
            "inchworm",
            "jam_sandwich",
            "mistmoth",
            "monarch_butterfly",
            "orchid_mantis",
            "pond_skater",
            "praying_mantis",
            "puddle_spider",
            "river_snail",
            "snowball_beetle",
            "worm"
        ],
        "loved": [
            "amber_trapped_insect",
            "bumblebee",
            "copper_beetle",
            "fairy_bee",
            "grilled_cheese",
            "jewel_beetle",
            "rhinoceros_beetle",
            "roly_poly",
            "sea_scarab",
            "strobe_firefly"
        ]
    },
    "seridia": {
        "name": "Priestess",
        "liked": [
            "crystal_rose",
            "black_tablet",
            "ore_pink_diamond",
            "ore_mistril",
            "mistril_ingot",
            "crystal",
            "red_wine",
            "crystal_caterpillar",
            "crystal_berry_pie",
            "iris",
            "cosmos",
            "rose"
        ],
        "loved": [
            "shadow_flower",
            "dragon_pact_tablet",
            "night_queen",
            "fog_orchid"
        ],
        "spoiler": 1
    },
    "merri": {
        "name": "Merri",
        "liked": [
            "alpaca_wool",
            "basic_wood",
            "bristle",
            "bull_horn",
            "clay",
            "coral",
            "crystal",
            "ore_diamond",
            "duck_feather",
            "glass",
            "hard_wood",
            "horse_hair",
            "latte",
            "obsidian",
            "paper",
            "ore_pink_diamond",
            "rabbit_wool",
            "feather",
            "sheep_wool",
            "ore_stone"
        ],
        "loved": [
            "golden_alpaca_wool",
            "golden_bristle",
            "golden_bull_horn",
            "golden_duck_feather",
            "golden_horse_hair",
            "golden_rabbit_wool",
            "golden_feather",
            "golden_sheep_wool",
            "perfect_diamond",
            "perfect_pink_diamond"
        ]
    },
    "holt": {
        "name": "Holt",
        "liked": [
            "potato",
            "beet",
            "broccoli",
            "cabbage",
            "carrot",
            "cauliflower",
            "chili_pepper",
            "corn",
            "cranberry",
            "cucumber",
            "daikon_radish",
            "onion",
            "peas",
            "pumpkin",
            "rice_stalk",
            "snow_peas",
            "strawberry",
            "sugar_cane",
            "sweet_potato",
            "turnip"
        ],
        "loved": [
            "flour",
            "gazpacho",
            "hard_wood",
            "loaded_baked_potato",
            "baked_potato",
            "stone_horse",
            "narrows_moss",
            "coffee",
            "watermelon",
            "wheat"
        ]
    },
    "celine": {
        "name": "Celine",
        "liked": [
            "catmint",
            "celosia",
            "chrysanthemum",
            "cosmos",
            "crocus",
            "daffodil",
            "daisy",
            "dandelion",
            "heather",
            "iris",
            "jasmine",
            "lilac",
            "marigold",
            "poinsettia",
            "rose_tea",
            "snapdragon",
            "spring_salad",
            "sunflower",
            "tulip",
            "viola"
        ],
        "loved": [
            "breath_of_fire",
            "crystal_rose",
            "essence_blossom",
            "frost_lily",
            "hydrangea",
            "middlemist",
            "plum_blossom",
            "rose",
            "snowdrop_anemone",
            "temple_flower"
        ]
    },
    "terithia": {
        "name": "Terithia",
        "liked": [
            "breaded_catfish",
            "canned_sardines",
            "clam_chowder",
            "crayfish_etouffee",
            "deep_sea_soup",
            "dried_squid",
            "fish_skewer",
            "fish_tacos",
            "grilled_eel_rice_bowl",
            "horseradish_salmon",
            "mackerel_sashimi",
            "pan_fried_bream",
            "pan_fried_salmon",
            "pan_fried_snapper",
            "red_snapper_sushi",
            "salmon_sashimi",
            "sesame_tuna_bowl",
            "smoked_trout_soup",
            "spicy_crab_sushi",
            "tuna_sashimi"
        ],
        "loved": [
            "cod_with_thyme",
            "fish_stew",
            "giant_fish_scale",
            "lobster_roll",
            "perch_risotto",
            "rubber_fish",
            "sea_bream_rice",
            "seafood_boil",
            "seafood_snow_pea_noodles",
            "sushi_platter"
        ]
    },
    "louis": {
        "name": "Louis",
        "liked": [
            "alpaca_wool",
            "breath_of_fire",
            "bristle",
            "cattail",
            "celosia",
            "crystal",
            "crystal_rose",
            "duck_feather",
            "essence_blossom",
            "feather",
            "cup_of_tea",
            "frost_lily",
            "horse_hair",
            "lilac",
            "marigold",
            "rabbit_wool",
            "shadow_flower",
            "snapdragon",
            "viola",
            "sheep_wool"
        ],
        "loved": [
            "golden_alpaca_wool",
            "golden_bristle",
            "golden_duck_feather",
            "golden_feather",
            "golden_horse_hair",
            "golden_rabbit_wool",
            "golden_sheep_wool",
            "middlemist",
            "red_wine",
            "white_wine"
        ]
    },
    "elsie": {
        "name": "Elsie",
        "liked": [
            "blackberry_jam",
            "blueberry_jam",
            "cherry_tart",
            "chrysanthemum",
            "cosmos",
            "crystal_berry_pie",
            "ore_diamond",
            "iris",
            "jasmine",
            "lilac",
            "marmalade",
            "moon_fruit_cake",
            "pomegranate_sorbet",
            "quiche",
            "red_wine",
            "rosehip_jam",
            "rose_hip",
            "tulip",
            "white_wine",
            "wild_berry_jam"
        ],
        "loved": [
            "alda_feather_pendant",
            "cranberry_orange_scone",
            "crystal_rose",
            "jasmine_tea",
            "mont_blanc",
            "paper",
            "perfect_diamond",
            "poached_pear",
            "rose",
            "wildberry_scone"
        ]
    },
    "juniper": {
        "name": "Juniper",
        "liked": [
            "crunchy_chickpeas",
            "crystal",
            "fog_orchid",
            "frog",
            "latte",
            "middlemist",
            "morel_mushroom",
            "nettle",
            "newt",
            "night_queen",
            "essence_blossom",
            "poinsettia",
            "red_toadstool",
            "red_wine",
            "monster_powder",
            "shadow_flower",
            "spell_fruit",
            "toasted_sunflower_seeds",
            "water_chestnut_fritters",
            "white_wine"
        ],
        "loved": [
            "ancient_royal_scepter",
            "black_tablet",
            "crystal_rose",
            "fish_tacos",
            "golden_cookies",
            "hardened_essence",
            "moon_fruit_cake",
            "mushroom_brew",
            "pizza",
            "spell_fruit_parfait"
        ]
    },
    "henrietta": {
        "name": "Henrietta",
        "liked": [
            "apple",
            "blackberry",
            "blueberry",
            "broccoli",
            "cherry",
            "chestnut",
            "coconut",
            "cranberry",
            "cucumber",
            "grass_seed",
            "moon_fruit",
            "orange",
            "peach",
            "pear",
            "peas",
            "pomegranate",
            "pumpkin",
            "wild_berries",
            "wild_grapes",
            "wintergreen_berry"
        ],
        "loved": [
            "berry_bowl",
            "animal_currency",
            "corn",
            "glowberry",
            "grilled_corn",
            "strawberry",
            "watermelon",
            "quality_small_animal_feed",
            "deluxe_small_animal_feed",
            "ultimate_small_animal_feed"
        ]
    },
    "landen": {
        "name": "Landen",
        "liked": [
            "basic_wood",
            "bristle",
            "bull_horn",
            "canned_sardines",
            "clay",
            "coconut",
            "coconut_milk",
            "crystal",
            "deep_sea_soup",
            "duck_feather",
            "glass",
            "horse_hair",
            "obsidian",
            "paper",
            "feather",
            "ore_stone",
            "shards",
            "tomato_soup",
            "vegetable_pot_pie",
            "vegetable_soup"
        ],
        "loved": [
            "coconut_cream_pie",
            "golden_bristle",
            "golden_bull_horn",
            "golden_cheesecake",
            "golden_cookies",
            "golden_duck_feather",
            "golden_horse_hair",
            "golden_feather",
            "hard_wood",
            "shard_mass"
        ]
    },
    "dell": {
        "name": "Dell",
        "liked": [
            "apple",
            "basic_wood",
            "blackberry",
            "caramel_candy",
            "cattail",
            "clay",
            "frog",
            "glowberry_cookies",
            "grape_juice",
            "grilled_cheese",
            "hot_cocoa",
            "sour_lemon_cake",
            "lemonade",
            "lightning_dragonfly",
            "monster_cookie",
            "pudding",
            "snail",
            "ore_stone",
            "trail_mix",
            "turtle"
        ],
        "loved": [
            "alda_bronze_sword",
            "aldarian_sword",
            "apple_juice",
            "bullfrog",
            "caldosian_sword",
            "chocolate",
            "golden_cookies",
            "hermit_crab",
            "ice_cream_sundae",
            "jam_sandwich"
        ]
    },
    "nora": {
        "name": "Nora",
        "liked": [
            "baked_potato",
            "beet_salad",
            "braised_burdock",
            "braised_carrots",
            "butter",
            "cabbage_slaw",
            "candied_lemon_peel",
            "coconut_milk",
            "coffee",
            "cucumber_salad",
            "grilled_corn",
            "latte",
            "poached_pear",
            "salted_watermelon",
            "sesame_broccoli",
            "simmered_daikon",
            "sliced_turnip",
            "spicy_water_chestnuts",
            "strawberries_and_cream",
            "tomato_soup"
        ],
        "loved": [
            "ancient_gold_coin",
            "cherry_cobbler",
            "fried_rice",
            "onion_soup",
            "peaches_and_cream",
            "pumpkin_stew",
            "roasted_cauliflower",
            "roasted_sweet_potato",
            "sauteed_snow_peas",
            "toasted_sunflower_seeds"
        ]
    },
    "ryis": {
        "name": "Ryis",
        "liked": [
            "basic_wood",
            "beer",
            "bread",
            "bristle",
            "bull_horn",
            "clay",
            "cranberry_orange_scone",
            "crystal",
            "duck_feather",
            "feather",
            "garlic_bread",
            "glass",
            "glowberry_cookies",
            "horse_hair",
            "iced_coffee",
            "lilac",
            "obsidian",
            "paper",
            "ore_stone",
            "strawberry_shortcake"
        ],
        "loved": [
            "golden_bristle",
            "golden_bull_horn",
            "golden_cheesecake",
            "golden_cookies",
            "golden_duck_feather",
            "golden_feather",
            "golden_horse_hair",
            "hard_wood",
            "lobster_roll",
            "veggie_sub_sandwich"
        ]
    },
    "caldarus": {
        "name": "Caldarus",
        "liked": [
            "beet_soup",
            "breath_of_fire",
            "chili_coconut_curry",
            "caldosian_chocolate_cake",
            "crab_cakes",
            "fish_tacos",
            "golden_cheesecake",
            "golden_cookies",
            "ice_cream_sundae",
            "incredibly_hot_pot",
            "lobster_roll",
            "marigold",
            "mushroom_steak_dinner",
            "perch_risotto",
            "spirit_mushroom_tea",
            "pumpkin_pie",
            "sea_bream_rice",
            "spell_fruit_parfait",
            "vegetable_pot_pie",
            "vegetable_quiche"
        ],
        "loved": [
            "apple_honey_curry",
            "fried_rice",
            "harvest_plate",
            "mont_blanc",
            "seafood_boil",
            "seafood_snow_pea_noodles",
            "spring_galette",
            "statuette_of_caldarus",
            "sushi_platter",
            "veggie_sub_sandwich"
        ]
    },
    "hayden": {
        "name": "Hayden",
        "liked": [
            "apple_pie",
            "butter",
            "cheese",
            "coconut_cream_pie",
            "coffee",
            "crystal_berry_pie",
            "duck_egg",
            "duck_mayonnaise",
            "egg",
            "lemon_pie",
            "loaded_baked_potato",
            "mayonnaise",
            "cow_milk",
            "mushroom_steak_dinner",
            "pumpkin_stew",
            "quiche",
            "sweet_potato_pie",
            "cup_of_tea",
            "vegetable_pot_pie",
            "wildberry_pie"
        ],
        "loved": [
            "golden_butter",
            "golden_cheese",
            "golden_duck_egg",
            "golden_duck_mayonnaise",
            "golden_egg",
            "golden_mayonnaise",
            "golden_cow_milk",
            "pumpkin_pie",
            "stone_horse",
            "vegetable_quiche"
        ]
    },
    "adeline": {
        "name": "Adeline",
        "liked": [
            "candied_lemon_peel",
            "ore_diamond",
            "heather",
            "lemon",
            "sour_lemon_cake",
            "lemonade",
            "ore_mistril",
            "paper",
            "peach",
            "pineshroom_toast",
            "ore_pink_diamond",
            "pumpkin_stew",
            "red_wine",
            "snapdragon",
            "spicy_cheddar_biscuit",
            "tulip",
            "vegetable_soup",
            "white_wine",
            "wildberry_pie",
            "wildberry_scone"
        ],
        "loved": [
            "coffee",
            "gazpacho",
            "lemon_pie",
            "middlemist",
            "mistril_ingot",
            "peaches_and_cream",
            "perfect_pink_diamond",
            "plum_blossom",
            "pumpkin_pie",
            "cup_of_tea"
        ]
    },
    "taliferro": {
        "name": "Taliferro",
        "liked": [
            "chili_coconut_curry",
            "coconut_cream_pie",
            "crab_cakes",
            "fish_tacos",
            "glowberry_cookies",
            "golden_cheesecake",
            "golden_cookies",
            "herb_salad",
            "ice_cream_sundae",
            "incredibly_hot_pot",
            "lobster_roll",
            "mushroom_steak_dinner",
            "perch_risotto",
            "pumpkin_pie",
            "red_wine",
            "sea_bream_rice",
            "vegetable_pot_pie",
            "vegetable_quiche",
            "veggie_sub_sandwich",
            "white_wine"
        ],
        "loved": [
            "apple_honey_curry",
            "beet_soup",
            "fried_rice",
            "harvest_plate",
            "mont_blanc",
            "seafood_boil",
            "seafood_snow_pea_noodles",
            "spell_fruit_parfait",
            "spring_galette",
            "sushi_platter"
        ]
    },
    "hemlock": {
        "name": "Hemlock",
        "liked": [
            "basil",
            "chili_pepper",
            "coffee",
            "crunchy_chickpeas",
            "dried_squid",
            "honey",
            "lemon",
            "roasted_chestnuts",
            "rock_salt",
            "sesame_broccoli",
            "spicy_cheddar_biscuit",
            "grape_juice",
            "spicy_crab_sushi",
            "spicy_water_chestnuts",
            "summer_salad",
            "tea",
            "thyme",
            "toasted_sunflower_seeds",
            "trail_mix",
            "water_chestnut_fritters"
        ],
        "loved": [
            "beer",
            "chili_coconut_curry",
            "crayfish_etouffee",
            "crispy_fried_earthshroom",
            "caldosian_drinking_horn",
            "hot_toddy",
            "incredibly_hot_pot",
            "white_wine",
            "wild_grapes",
            "spicy_corn"
        ]
    },
    "olric": {
        "name": "Olric",
        "liked": [
            "ore_copper",
            "crystal",
            "ore_diamond",
            "ore_emerald",
            "ore_gold",
            "hard_boiled_egg",
            "ore_iron",
            "miners_mushroom_stew",
            "ore_mistril",
            "obsidian",
            "ore_pink_diamond",
            "rock_with_a_hole",
            "rockroot",
            "ore_ruby",
            "ore_sapphire",
            "ore_silver",
            "ore_stone",
            "stone_horse",
            "rock_statue",
            "weightless_stone"
        ],
        "loved": [
            "perfect_copper_ore",
            "perfect_diamond",
            "perfect_emerald",
            "perfect_gold_ore",
            "perfect_iron_ore",
            "perfect_mistril_ore",
            "perfect_pink_diamond",
            "perfect_ruby",
            "perfect_sapphire",
            "perfect_silver_ore"
        ]
    },
    "josephine": {
        "name": "Josephine",
        "liked": [
            "breath_of_fire",
            "chili_pepper",
            "curry_powder",
            "essence_blossom",
            "flour",
            "honey",
            "jam_sandwich",
            "jasmine",
            "oil",
            "rice",
            "rose",
            "soy_sauce",
            "spicy_cheddar_biscuit",
            "spicy_corn",
            "spicy_crab_sushi",
            "spicy_water_chestnuts",
            "sugar",
            "sunflower",
            "tea",
            "wild_berry_jam"
        ],
        "loved": [
            "jasmine_tea",
            "green_tea",
            "lavender_tea",
            "quiche",
            "roasted_rice_tea",
            "rose_tea",
            "cup_of_tea",
            "incredibly_hot_pot",
            "chili_coconut_curry",
            "crayfish_etouffee"
        ]
    },
    "reina": {
        "name": "Reina",
        "liked": [
            "cauliflower_curry",
            "cheese",
            "cod_with_thyme",
            "coffee",
            "crystal_berry_pie",
            "daffodil",
            "deep_sea_soup",
            "flour",
            "garlic",
            "garlic_bread",
            "grilled_cheese",
            "iced_coffee",
            "miners_mushroom_stew",
            "pizza",
            "rice",
            "spicy_cheddar_biscuit",
            "sugar",
            "turnip_and_potato_gratin",
            "upper_mines_mushroom",
            "wildberry_pie"
        ],
        "loved": [
            "apple_honey_curry",
            "breaded_catfish",
            "cabbage_slaw",
            "ice_cream_sundae",
            "incredibly_hot_pot",
            "rosemary_garlic_noodles",
            "seafood_boil",
            "seafood_snow_pea_noodles",
            "spell_fruit_parfait",
            "sushi_platter"
        ]
    },
    "stillwell": {
        "name": "Stillwell",
        "liked": [
            "glass",
            "muttering_cube",
            "crystal",
            "night_queen",
            "shardfin",
            "shadow_flower",
            "crystal_rose",
            "red_toadstool",
            "middlemist",
            "crystal_wing_moth",
            "coffee",
            "cup_of_tea"
        ],
        "loved": [
            "fog_orchid",
            "black_tablet",
            "weightless_stone",
            "red_wine"
        ],
        "spoiler": 1
    },
    "dozy": {
        "name": "Dozy",
        "liked": [
            "butterfly",
            "carrot",
            "cicada",
            "cod",
            "cricket",
            "duck_egg",
            "egg",
            "firefly",
            "fuzzy_moth",
            "grasshopper",
            "mackerel",
            "monster_shell",
            "monster_hoop",
            "pumpkin",
            "red_snapper",
            "rockroot",
            "salmon",
            "sardine",
            "sod",
            "tuna"
        ],
        "loved": [
            "basic_wood",
            "hard_boiled_egg",
            "catfish",
            "crystalline_cricket",
            "golden_duck_egg",
            "golden_egg",
            "hard_wood",
            "dog_treat",
            "petrified_wood",
            "tiny_dinosaur_skeleton"
        ]
    }
}