var objScrolls =
{
    "woodcrafting": {
        "name": "Woodcrafting",
        "subcategories": {
            "0": {
                "name": "Automation",
                "items": [
                    "ocarina_sprite_statue",
                    "big_bell",
                    "water_sprite_statue_v1",
                    "water_sprite_statue_v2",
                    "water_sprite_statue_v3",
                    "water_sprite_statue_v4",
                    "water_sprite_statue_v5"
                ]
            },
            "1": {
                "name": "Starter Farm Set",
                "items": [
                    "starter_bird_house_red",
                    "campfire",
                    "dirt_dot_one",
                    "dirt_dot_two",
                    "dirt_dot_three",
                    "dirt_clear",
                    "farm_house_calendar",
                    "field_grass_two",
                    "field_flower_two",
                    "field_grass",
                    "field_clear",
                    "field_flower",
                    "spooky_haybale",
                    "picket_fence",
                    "starter_potted_plant",
                    "starter_scarecrow",
                    "starter_shipping_box",
                    "farm_bridge",
                    "starter_stone_path",
                    "starter_stone_path_double",
                    "stone_wall",
                    "starter_well",
                    "starter_wheelbarrow",
                    "starter_wood_fence"
                ]
            },
            "2": {
                "name": "Worn Set",
                "items": [
                    "journal",
                    "worn_bed",
                    "worn_chair",
                    "worn_fireplace",
                    "worn_flooring",
                    "worn_garden_lamp",
                    "worn_nightstand",
                    "worn_rug",
                    "worn_table",
                    "worn_wallpaper",
                    "worn_well",
                    "worn_window"
                ]
            },
            "3": {
                "name": "Basic Set",
                "items": [
                    "basic_area_rug_green",
                    "basic_area_rug_yellow",
                    "basic_bookshelf_oak",
                    "basic_bookshelf_walnut",
                    "basic_chair_oak",
                    "basic_chair_walnut",
                    "basic_doormat_green",
                    "basic_doormat_yellow",
                    "basic_bed_double_oak",
                    "basic_bed_double_walnut",
                    "basic_dresser_oak",
                    "basic_dresser_walnut",
                    "basic_flooring_oak",
                    "basic_flooring_walnut",
                    "basic_flower_pot_orange",
                    "basic_flower_pot_white",
                    "basic_nightstand_oak",
                    "basic_nightstand_walnut",
                    "basic_oil_lamp_grey",
                    "basic_oil_lamp_yellow",
                    "basic_bed_oak",
                    "basic_bed_walnut",
                    "basic_table_oak",
                    "basic_table_walnut",
                    "basic_wallpaper_oak",
                    "basic_wallpaper_walnut",
                    "basic_wall_window_oak",
                    "basic_wall_window_walnut"
                ]
            },
            "4": {
                "name": "Basic Chest Set",
                "items": [
                    "basic_wood_chest_black",
                    "basic_wood_chest_blue",
                    "basic_wood_chest_cottage",
                    "basic_wood_chest_dark",
                    "basic_wood_chest_green",
                    "basic_wood_chest_haunted_attic",
                    "basic_wood_chest_light",
                    "basic_wood_chest_medium",
                    "basic_wood_chest_orange",
                    "basic_wood_chest_pink",
                    "basic_wood_chest_purple",
                    "basic_wood_chest_red",
                    "basic_wood_chest_white",
                    "basic_wood_chest_witch_queen",
                    "basic_wood_chest_yellow"
                ]
            },
            "5": {
                "name": "Lovely Cottage Set",
                "items": [
                    "cottage_chair_ash",
                    "cottage_chair_oak",
                    "cottage_bed_double_ash",
                    "cottage_bed_double_oak",
                    "cottage_dresser_ash",
                    "cottage_dresser_oak",
                    "cottage_flooring_ash",
                    "cottage_flooring_oak",
                    "cottage_fridge_ash",
                    "cottage_fridge_oak",
                    "cottage_nightstand_ash",
                    "cottage_nightstand_oak",
                    "cottage_plant_shelf_ash",
                    "cottage_plant_shelf_oak",
                    "cottage_potted_fig_ash",
                    "cottage_potted_fig_oak",
                    "cottage_potted_flowers_ash",
                    "cottage_potted_flowers_oak",
                    "cottage_rug_ash",
                    "cottage_rug_oak",
                    "cottage_bed_ash",
                    "cottage_bed_oak",
                    "cottage_table_ash",
                    "cottage_table_oak",
                    "cottage_wall_flowers_ash",
                    "cottage_wall_flowers_oak",
                    "cottage_wallpaper_ash",
                    "cottage_wallpaper_oak",
                    "cottage_wall_window_ash",
                    "cottage_wall_window_oak"
                ]
            },
            "6": {
                "name": "Rustic Cabin Set",
                "items": [
                    "cabin_bed_cherry",
                    "cabin_bed_oak",
                    "cabin_bed_walnut",
                    "cabin_bookshelf_cherry",
                    "cabin_bookshelf_oak",
                    "cabin_bookshelf_walnut",
                    "cabin_chair_cherry",
                    "cabin_chair_oak",
                    "cabin_chair_walnut",
                    "cabin_bed_double_cherry",
                    "cabin_bed_double_oak",
                    "cabin_bed_double_walnut",
                    "cabin_dresser_cherry",
                    "cabin_dresser_oak",
                    "cabin_dresser_walnut",
                    "cabin_firewood_cherry",
                    "cabin_firewood_oak",
                    "cabin_firewood_walnut",
                    "cabin_flooring_cherry",
                    "cabin_flooring_oak",
                    "cabin_flooring_walnut",
                    "cabin_lamp_cherry",
                    "cabin_lamp_oak",
                    "cabin_lamp_walnut",
                    "cabin_nightstand_cherry",
                    "cabin_nightstand_oak",
                    "cabin_nightstand_walnut",
                    "cabin_stove_cherry",
                    "cabin_stove_walnut",
                    "cabin_table_cherry",
                    "cabin_table_oak",
                    "cabin_table_walnut",
                    "cabin_wall_shelf_cherry",
                    "cabin_wall_shelf_oak",
                    "cabin_wall_shelf_walnut",
                    "cabin_wallpaper_cherry",
                    "cabin_wallpaper_oak",
                    "cabin_wallpaper_walnut",
                    "cabin_wall_window_cherry",
                    "cabin_wall_window_oak",
                    "cabin_wall_window_walnut"
                ]
            },
            "7": {
                "name": "Haunted Attic Set",
                "items": [
                    "haunted_attic_wall_cobweb_left",
                    "haunted_attic_wall_cobweb_left_dark",
                    "haunted_attic_wall_cobweb_right",
                    "haunted_attic_wall_cobweb_right_dark",
                    "haunted_attic_armoire_dark",
                    "haunted_attic_armoire_dusty",
                    "haunted_attic_bed_dark",
                    "haunted_attic_bed_dusty",
                    "haunted_attic_chair_dark",
                    "haunted_attic_chair_dusty",
                    "haunted_attic_double_bed_dark",
                    "haunted_attic_double_bed_dusty",
                    "haunted_attic_dress_form_dark",
                    "haunted_attic_dress_form_dusty",
                    "haunted_attic_flooring_dark",
                    "haunted_attic_flooring_dusty",
                    "haunted_attic_nightstand_dark",
                    "haunted_attic_nightstand_dusty",
                    "haunted_attic_rocking_chair_dark",
                    "haunted_attic_rocking_chair_dusty",
                    "haunted_attic_table_dark",
                    "haunted_attic_table_dusty",
                    "haunted_attic_wall_shelf_dark",
                    "haunted_attic_wall_shelf_dusty",
                    "haunted_attic_wallpaper_dark",
                    "haunted_attic_wallpaper_dusty",
                    "haunted_attic_wall_window_dark",
                    "haunted_attic_wall_window_dusty",
                    "haunted_attic_candle_single",
                    "haunted_attic_candle_single_dark",
                    "haunted_attic_candle_cluster",
                    "haunted_attic_candle_cluster_dark"
                ]
            },
            "8": {
                "name": "Explorer Set",
                "items": [
                    "explorer_bed_beige",
                    "explorer_bed_brown",
                    "explorer_bed_green",
                    "explorer_chair_beige",
                    "explorer_chair_brown",
                    "explorer_chair_green",
                    "explorer_double_bed_beige",
                    "explorer_double_bed_brown",
                    "explorer_double_bed_green",
                    "explorer_flooring_beige",
                    "explorer_flooring_brown",
                    "explorer_flooring_green",
                    "explorer_globe_beige",
                    "explorer_globe_brown",
                    "explorer_globe_green",
                    "explorer_lamp_beige",
                    "explorer_lamp_brown",
                    "explorer_lamp_green",
                    "explorer_rug_beige",
                    "explorer_rug_brown",
                    "explorer_rug_green",
                    "explorer_trunk_table_beige",
                    "explorer_trunk_table_brown",
                    "explorer_trunk_table_green",
                    "explorer_wallpaper_beige",
                    "explorer_wallpaper_brown",
                    "explorer_wallpaper_green"
                ]
            },
            "9": {
                "name": "Fishing Set",
                "items": [
                    "fishing_plaque_blue",
                    "fishing_plaque_red",
                    "fish_plush_toy",
                    "fishing_tank_gold",
                    "fishing_tank_silver",
                    "fishing_bed_blue",
                    "fishing_bed_red",
                    "fishing_chair_blue",
                    "fishing_chair_red",
                    "fishing_double_bed_blue",
                    "fishing_double_bed_red",
                    "fishing_flooring_blue",
                    "fishing_flooring_red",
                    "fishing_rug_blue",
                    "fishing_rug_red",
                    "fishing_table_blue",
                    "fishing_table_red",
                    "fishing_trophy_shelf_blue",
                    "fishing_trophy_shelf_red",
                    "fishing_wallpaper_blue",
                    "fishing_wallpaper_red",
                    "fishing_lamp_blue",
                    "fishing_lamp_red",
                    "fishing_oar_wall_decor_blue",
                    "fishing_oar_wall_decor_red",
                    "octopus_plushie",
                    "fishing_window_gold",
                    "fishing_window_silver"
                ]
            },
            "10": {
                "name": "Spring Set",
                "items": [
                    "spring_bed_orange",
                    "spring_bed_pink",
                    "spring_bed_purple",
                    "spring_double_bed_orange",
                    "spring_double_bed_pink",
                    "spring_double_bed_purple",
                    "spring_flooring_orange",
                    "spring_flooring_pink",
                    "spring_flooring_purple",
                    "spring_rug_orange",
                    "spring_rug_pink",
                    "spring_rug_purple",
                    "spring_lamp_orange",
                    "spring_lamp_pink",
                    "spring_lamp_purple",
                    "spring_potted_tree_orange",
                    "spring_potted_tree_pink",
                    "spring_potted_tree_purple",
                    "spring_sofa_orange",
                    "spring_sofa_pink",
                    "spring_sofa_purple",
                    "spring_wallpaper_orange",
                    "spring_wallpaper_pink",
                    "spring_wallpaper_purple"
                ]
            },
            "11": {
                "name": "Summer Set",
                "items": [
                    "summer_bed_red",
                    "summer_bed_yellow",
                    "summer_chair_red",
                    "summer_chair_yellow",
                    "summer_double_bed_red",
                    "summer_double_bed_yellow",
                    "summer_flooring_red",
                    "summer_flooring_yellow",
                    "summer_rug_red",
                    "summer_rug_yellow",
                    "summer_jar_lamp_red",
                    "summer_jar_lamp_yellow",
                    "summer_table_red",
                    "summer_table_yellow",
                    "summer_wallpaper_red",
                    "summer_wallpaper_yellow"
                ]
            },
            "12": {
                "name": "Fall Set",
                "items": [
                    "fall_table_cream",
                    "fall_table_orange",
                    "fall_table_red",
                    "fall_table_yellow",
                    "fall_double_bed_cream",
                    "fall_double_bed_orange",
                    "fall_double_bed_red",
                    "fall_double_bed_yellow",
                    "fall_bed_cream",
                    "fall_bed_orange",
                    "fall_bed_red",
                    "fall_bed_yellow"
                ]
            },
            "13": {
                "name": "Mermaid Set",
                "items": [
                    "mermaid_double_bed_v1",
                    "mermaid_double_bed_v2",
                    "mermaid_double_bed_v3",
                    "mermaid_bed_v1",
                    "mermaid_bed_v2",
                    "mermaid_bed_v3"
                ]
            },
            "14": {
                "name": "Emerald Set",
                "items": [
                    "emerald_chair_v1",
                    "emerald_chair_v2",
                    "emerald_double_bed_v1",
                    "emerald_double_bed_v2",
                    "emerald_nightstand_v1",
                    "emerald_nightstand_v2",
                    "emerald_rug_v1",
                    "emerald_rug_v2",
                    "emerald_bed_v1",
                    "emerald_bed_v2",
                    "emerald_wallpaper_v1",
                    "emerald_wallpaper_v2"
                ]
            },
            "15": {
                "name": "Witch Queen Set",
                "items": [
                    "witch_queen_bed",
                    "witch_queen_cauldron",
                    "witch_queen_chair",
                    "witch_queen_double_bed",
                    "witch_queen_dressing_table",
                    "witch_queen_flooring",
                    "witch_queen_moon_lamp",
                    "witch_queen_nightstand",
                    "witch_queen_pillar",
                    "witch_queen_rug",
                    "witch_queen_table",
                    "witch_queen_throne",
                    "witch_queen_wallpaper"
                ]
            },
            "16": {
                "name": "Bakery Decor Set",
                "items": [
                    "bakery_bread_basket_coffee",
                    "bakery_bread_basket_pastel",
                    "bakery_cookie_jar_coffee",
                    "bakery_cookie_jar_pastel",
                    "bakery_cutting_board_coffee",
                    "bakery_cutting_board_pastel",
                    "bakery_cake_case_coffee",
                    "bakery_cake_case_pastel",
                    "bakery_cake_coffee",
                    "bakery_cake_pastel",
                    "bakery_cake_slice_coffee",
                    "bakery_cake_slice_pastel"
                ]
            },
            "17": {
                "name": "Picnic Decor Set",
                "items": [
                    "picnic_basket_pink",
                    "picnic_basket_red",
                    "picnic_basket_yellow",
                    "picnic_rug_pink",
                    "picnic_rug_red",
                    "picnic_rug_yellow",
                    "picnic_hamburger_plate",
                    "picnic_donut_plate",
                    "picnic_pie_plate_pink",
                    "picnic_pie_plate_red",
                    "picnic_pie_plate_yellow",
                    "picnic_sandwich_plate",
                    "picnic_place_setting_pink",
                    "picnic_place_setting_red",
                    "picnic_place_setting_yellow",
                    "picnic_sunflower_vase_pink",
                    "picnic_sunflower_vase_red",
                    "picnic_sunflower_vase_yellow"
                ]
            },
            "18": {
                "name": "Ornate Rug Set",
                "items": [
                    "ornate_rug_large_rectangle_blue",
                    "ornate_rug_large_rectangle_cream",
                    "ornate_rug_large_rectangle_red",
                    "ornate_rug_large_round_blue",
                    "ornate_rug_large_round_cream",
                    "ornate_rug_large_round_red",
                    "ornate_rug_large_square_blue",
                    "ornate_rug_large_square_cream",
                    "ornate_rug_large_square_red",
                    "ornate_rug_medium_round_blue",
                    "ornate_rug_medium_round_cream",
                    "ornate_rug_medium_round_red",
                    "ornate_rug_medium_square_blue",
                    "ornate_rug_medium_square_cream",
                    "ornate_rug_medium_square_red",
                    "ornate_rug_small_blue",
                    "ornate_rug_small_cream",
                    "ornate_rug_small_red"
                ]
            },
            "19": {
                "name": "Mineshaft Set",
                "items": [
                    "miners_minecart_v1",
                    "miners_minecart_v2",
                    "mines_wooden_arch",
                    "miners_crate_chair_v1",
                    "miners_crate_chair_v2",
                    "miners_floor_lamp_v1",
                    "miners_floor_lamp_v2",
                    "miners_flooring",
                    "miners_shelves_v1",
                    "miners_shelves_v2",
                    "miners_crate_chest_v1",
                    "miners_crate_chest_v2",
                    "miners_wallpaper",
                    "miners_wall_lamp_v1",
                    "miners_wall_lamp_v2",
                    "miners_copper_node",
                    "miners_ruby_rock"
                ]
            },
            "20": {
                "name": "Tide Set",
                "items": [
                    "coral_chair_blue",
                    "coral_chair_purple",
                    "coral_lamp_blue",
                    "coral_lamp_purple",
                    "coral_storage_chest_blue",
                    "coral_storage_chest_purple",
                    "coral_table_blue",
                    "coral_table_purple",
                    "coral_stone_archway",
                    "low_tide_flooring",
                    "ornamental_iron_node",
                    "ornamental_sapphire_rock",
                    "sand_rug",
                    "tide_touched_cavern_wall"
                ]
            },
            "21": {
                "name": "Cavern Set",
                "items": [
                    "cavern_floor_brazier_blue",
                    "cavern_floor_brazier_orange",
                    "cavern_floor_brazier_purple",
                    "cavern_crystal_lamp_green",
                    "cavern_crystal_lamp_pink",
                    "cavern_crystal_lamp_purple",
                    "cavern_hewn_rock_bookshelf",
                    "cavern_hewn_rock_table",
                    "cavern_mossy_rug_v1",
                    "cavern_mossy_rug_v2",
                    "cavern_mushroom_stool_green",
                    "cavern_mushroom_stool_pink",
                    "cavern_mushroom_stool_purple",
                    "cavern_emerald_rock",
                    "cavern_silver_node",
                    "cavern_rock_flooring",
                    "cavern_rock_wallpaper",
                    "cavern_stone_arch",
                    "cavern_wall_brazier_blue",
                    "cavern_wall_brazier_orange",
                    "cavern_wall_brazier_purple"
                ]
            },
            "22": {
                "name": "Lava Caves Set",
                "items": [
                    "lava_caves_stone_arch",
                    "lava_caves_flooring",
                    "lava_caves_wallpaper",
                    "lava_caves_obsidian_bed_blue",
                    "lava_caves_obsidian_bed_purple",
                    "lava_caves_obsidian_chair_blue",
                    "lava_caves_obsidian_chair_purple",
                    "lava_caves_obsidian_double_bed_blue",
                    "lava_caves_obsidian_double_bed_purple",
                    "lava_caves_obsidian_fence_blue",
                    "lava_caves_obsidian_fence_purple",
                    "lava_caves_obsidian_floor_lamp_blue",
                    "lava_caves_obsidian_floor_lamp_purple",
                    "lava_caves_obsidian_storage_chest_blue",
                    "lava_caves_obsidian_storage_chest_purple",
                    "lava_caves_obsidian_table_blue",
                    "lava_caves_obsidian_table_purple",
                    "lava_caves_diamond_rock",
                    "lava_caves_gold_node"
                ]
            },
            "23": {
                "name": "Spring Crop Sign Set",
                "items": [
                    "crop_sign_cabbage",
                    "crop_sign_carrot",
                    "crop_sign_cherry",
                    "crop_sign_chickpea",
                    "crop_sign_daffodil",
                    "crop_sign_lemon",
                    "crop_sign_lilac",
                    "crop_sign_mystery_bag",
                    "crop_sign_peas",
                    "crop_sign_potato",
                    "crop_sign_snowdrop_anemone",
                    "crop_sign_strawberry",
                    "crop_sign_temple_flower",
                    "crop_sign_tulip",
                    "crop_sign_turnip"
                ]
            },
            "24": {
                "name": "Summer Crop Sign Set",
                "items": [
                    "crop_sign_basil",
                    "crop_sign_catmint",
                    "crop_sign_chili_pepper",
                    "crop_sign_coconut",
                    "crop_sign_corn",
                    "crop_sign_cosmos",
                    "crop_sign_cucumber",
                    "crop_sign_daisy",
                    "crop_sign_dill",
                    "crop_sign_iris",
                    "crop_sign_marigold",
                    "crop_sign_night_queen",
                    "crop_sign_oregano",
                    "crop_sign_peach",
                    "crop_sign_pear",
                    "crop_sign_sage",
                    "crop_sign_sugar_cane",
                    "crop_sign_sunflower",
                    "crop_sign_tea",
                    "crop_sign_thyme",
                    "crop_sign_tomato",
                    "crop_sign_watermelon"
                ]
            },
            "25": {
                "name": "Fall Crop Sign Set",
                "items": [
                    "crop_sign_apple",
                    "crop_sign_broccoli",
                    "crop_sign_celosia",
                    "crop_sign_chrysanthemum",
                    "crop_sign_cranberry",
                    "crop_sign_garlic",
                    "crop_sign_heather",
                    "crop_sign_moon_fruit",
                    "crop_sign_onion",
                    "crop_sign_orange",
                    "crop_sign_pumpkin",
                    "crop_sign_rice",
                    "crop_sign_rosemary",
                    "crop_sign_sweet_potato",
                    "crop_sign_viola",
                    "crop_sign_wheat"
                ]
            },
            "26": {
                "name": "Winter Crop Sign Set",
                "items": [
                    "crop_sign_beet",
                    "crop_sign_burdock_root",
                    "crop_sign_cauliflower",
                    "crop_sign_daikon_radish",
                    "crop_sign_frost_lily",
                    "crop_sign_jasmine",
                    "crop_sign_poinsettia",
                    "crop_sign_pomegranate",
                    "crop_sign_snapdragon",
                    "crop_sign_snow_peas"
                ]
            },
            "27": {
                "name": "Faux Spring Plant Set",
                "items": [
                    "crop_faux_cabbage",
                    "crop_faux_carrot",
                    "crop_faux_chickpea",
                    "crop_faux_daffodil",
                    "crop_faux_dandelion",
                    "crop_faux_fennel",
                    "crop_faux_fiddlehead",
                    "crop_faux_lilac",
                    "crop_faux_mystery_bag",
                    "crop_faux_middlemist",
                    "crop_faux_morel_mushroom",
                    "crop_faux_nettle",
                    "crop_faux_peas",
                    "crop_faux_potato",
                    "crop_faux_snowdrop_anemone",
                    "crop_faux_strawberry",
                    "crop_faux_tulip",
                    "crop_faux_turnip",
                    "crop_faux_wild_leek"
                ]
            },
            "28": {
                "name": "Faux Summer Plant Set",
                "items": [
                    "crop_faux_basil",
                    "crop_faux_catmint",
                    "crop_faux_chili_pepper",
                    "crop_faux_corn",
                    "crop_faux_cosmos",
                    "crop_faux_cucumber",
                    "crop_faux_daisy",
                    "crop_faux_dill",
                    "crop_faux_iris",
                    "crop_faux_marigold",
                    "crop_faux_night_queen",
                    "crop_faux_oregano",
                    "crop_faux_sage",
                    "crop_faux_sesame",
                    "crop_faux_sugar_cane",
                    "crop_faux_sunflower",
                    "crop_faux_tea",
                    "crop_faux_thyme",
                    "crop_faux_tomato",
                    "crop_faux_watermelon"
                ]
            },
            "29": {
                "name": "Faux Fall Plant Set",
                "items": [
                    "crop_faux_broccoli",
                    "crop_faux_celosia",
                    "crop_faux_chestnut",
                    "crop_faux_chrysanthemum",
                    "crop_faux_cranberry",
                    "crop_faux_fog_orchid",
                    "crop_faux_garlic",
                    "crop_faux_heather",
                    "crop_faux_horseradish",
                    "crop_faux_moon_fruit",
                    "crop_faux_onion",
                    "crop_faux_pumpkin",
                    "crop_faux_rice",
                    "crop_faux_rosemary",
                    "crop_faux_sweet_potato",
                    "crop_faux_viola",
                    "crop_faux_wheat"
                ]
            },
            "30": {
                "name": "Faux Winter Plant Set",
                "items": [
                    "crop_faux_beet",
                    "crop_faux_burdock_root",
                    "crop_faux_cauliflower",
                    "crop_faux_crocus",
                    "crop_faux_daikon_radish",
                    "crop_faux_frost_lily",
                    "crop_faux_holly",
                    "crop_faux_ice_block",
                    "crop_faux_jasmine",
                    "crop_faux_oyster_mushroom",
                    "crop_faux_pineshroom",
                    "crop_faux_poinsettia",
                    "crop_faux_snapdragon",
                    "crop_faux_snow_peas"
                ]
            },
            "31": {
                "name": "Faux Deep Woods Set",
                "items": [
                    "crop_faux_spirit_mushroom",
                    "crop_faux_temple_flower",
                    "crop_faux_thorn_vine",
                    "crop_faux_walnut"
                ]
            },
            "32": {
                "name": "Faux Mines Plant Set",
                "items": [
                    "crop_faux_ash_mushroom",
                    "crop_faux_breath_of_fire",
                    "crop_faux_crystal_berries",
                    "crop_faux_crystal_rose",
                    "crop_faux_earthshroom",
                    "crop_faux_flame_pepper",
                    "crop_faux_hot_potato",
                    "crop_faux_cave_kelp",
                    "crop_faux_lava_chestnuts",
                    "crop_faux_mines_mussels",
                    "crop_faux_narrows_moss",
                    "crop_faux_rockroot",
                    "crop_faux_sea_grapes",
                    "crop_faux_shadow_flower",
                    "crop_faux_shale_grass",
                    "crop_faux_sweetroot",
                    "crop_faux_tide_lettuce",
                    "crop_faux_upper_mines_mushroom"
                ]
            },
            "33": {
                "name": "Faux Shell Set",
                "items": [
                    "crop_faux_blue_conch_shell",
                    "crop_faux_pink_scallop_shell",
                    "crop_faux_sand_dollar",
                    "crop_faux_spirula_shell"
                ]
            },
            "34": {
                "name": "Chess Piece Set",
                "items": [
                    "chess_bishop_black",
                    "chess_bishop_light_wood",
                    "chess_bishop_purple",
                    "chess_bishop_white",
                    "chess_king_black",
                    "chess_king_light_wood",
                    "chess_king_purple",
                    "chess_king_white",
                    "chess_knight_black",
                    "chess_knight_light_wood",
                    "chess_knight_purple",
                    "chess_knight_white",
                    "chess_pawn_black",
                    "chess_pawn_light_wood",
                    "chess_pawn_purple",
                    "chess_pawn_white",
                    "chess_queen_black",
                    "chess_queen_light_wood",
                    "chess_queen_purple",
                    "chess_queen_white",
                    "chess_rook_black",
                    "chess_rook_light_wood",
                    "chess_rook_purple",
                    "chess_rook_white",
                    "chess_table_black",
                    "chess_table_light_wood",
                    "chess_table_purple",
                    "chess_table_white"
                ]
            },
            "35": {
                "name": "Insect Set",
                "items": [
                    "bumblebee_plushie",
                    "butterfly_bed_v1",
                    "butterfly_bed_v2",
                    "butterfly_bed_v3",
                    "butterfly_double_bed_v1",
                    "butterfly_double_bed_v2",
                    "butterfly_double_bed_v3",
                    "butterfly_wall_lamp_bronze",
                    "butterfly_wall_lamp_gold",
                    "butterfly_wall_lamp_silver",
                    "caterpillar_chair_v1",
                    "caterpillar_chair_v2",
                    "caterpillar_chair_v3",
                    "firefly_wall_string_lights_blue",
                    "firefly_wall_string_lights_pink",
                    "firefly_wall_string_lights_purple",
                    "firefly_wall_string_lights_white",
                    "firefly_wall_string_lights_yellow",
                    "insect_flooring_v1",
                    "insect_flooring_v2",
                    "insect_flooring_v3",
                    "insect_rug_v1",
                    "insect_rug_v2",
                    "insect_rug_v3",
                    "insect_wallpaper_v1",
                    "insect_wallpaper_v2",
                    "insect_wallpaper_v3",
                    "ladybug_table_v1",
                    "ladybug_table_v2",
                    "ladybug_table_v3",
                    "moth_lamp_v1",
                    "moth_lamp_v2",
                    "moth_lamp_v3"
                ]
            },
            "36": {
                "name": "Stone Garden Set",
                "items": [
                    "large_paving_stone_v1",
                    "large_paving_stone_v2",
                    "large_paving_stone_v3",
                    "stone_bench_v1",
                    "stone_bench_v2",
                    "stone_bench_v3",
                    "stone_lamp_v1",
                    "stone_lamp_v2",
                    "stone_lamp_v3",
                    "stone_storage_chest_v1",
                    "stone_storage_chest_v2",
                    "stone_storage_chest_v3",
                    "stone_table_v1",
                    "stone_table_v2",
                    "stone_table_v3"
                ]
            },
            "37": {
                "name": "Mistrian History Set",
                "items": [
                    "alda_pot_replica_blue",
                    "alda_pot_replica_gold",
                    "alda_pot_replica_green",
                    "alda_pot_replica_purple",
                    "alda_pot_replica_red",
                    "mistria_history_scroll_v1",
                    "hero_shield_bronze",
                    "hero_shield_gold",
                    "hero_shield_silver",
                    "dragon_priestess_fountain_v1",
                    "dragon_priestess_fountain_v2",
                    "dragon_priestess_fountain_v3",
                    "dragon_statue_replica_v1",
                    "dragon_statue_replica_v2",
                    "gryphon_statue_replica_v1",
                    "gryphon_statue_replica_v2",
                    "gryphon_statue_replica_v3",
                    "mistria_history_book_v1",
                    "mistria_wall_map_v1",
                    "obelisk_beige",
                    "obelisk_black",
                    "obelisk_pink",
                    "obelisk_plum",
                    "obelisk_teal",
                    "obelisk_white",
                    "ornate_flagstone_v1",
                    "ornate_flagstone_v2",
                    "ornate_flagstone_v3",
                    "royal_chest_blue",
                    "royal_chest_dark_wood",
                    "royal_chest_green",
                    "royal_chest_purple",
                    "royal_chest_red",
                    "royal_chest_wood",
                    "stone_dragon_figure_v1",
                    "stone_dragon_figure_v2",
                    "stone_dragon_figure_v3"
                ]
            },
            "38": {
                "name": "Dragon Claw Altar Set",
                "items": [
                    "dragon_altar_earth",
                    "dragon_altar_fire",
                    "dragon_altar_ruins",
                    "dragon_altar_water"
                ]
            },
            "39": {
                "name": "Shooting Star Set",
                "items": [
                    "star_cushion_blue",
                    "star_cushion_light_blue",
                    "star_cushion_pink",
                    "star_cushion_purple",
                    "star_cushion_white",
                    "star_cushion_yellow",
                    "star_lantern_blue",
                    "star_lantern_pink",
                    "star_lantern_purple",
                    "star_lantern_white",
                    "star_lantern_yellow",
                    "star_viewing_blanket_blue",
                    "star_viewing_blanket_pink",
                    "star_viewing_blanket_purple",
                    "star_viewing_blanket_yellow"
                ]
            },
            "40": {
                "name": "Training Dummy Set",
                "items": [
                    "training_dummy_clod",
                    "training_dummy_mushroom",
                    "training_dummy_sapling"
                ]
            },
            "41": {
                "name": "Tabletop Clutter Set",
                "items": [
                    "glass_absinthe",
                    "basket",
                    "beer_mug",
                    "tea_black",
                    "candle",
                    "candle_chamberstick",
                    "glass_cocktail",
                    "coffee_mug_v1",
                    "coffee_mug_v2",
                    "coffee_mug_v3",
                    "espresso_cup_v1",
                    "espresso_cup_v2",
                    "espresso_cup_v3",
                    "green_bottle",
                    "tea_green",
                    "jar_large",
                    "glass_lemonade",
                    "box_medium_v1",
                    "jar_medium",
                    "glass_milk",
                    "notepad_white",
                    "notepad_yellow",
                    "jar_pair",
                    "paper_stack",
                    "wine_glass_red",
                    "wine_glass_rose",
                    "box_small_v1",
                    "box_small_v2",
                    "jar_small",
                    "small_vase_v1",
                    "small_vase_v2",
                    "small_vase_v3",
                    "small_vase_v4",
                    "glass_water",
                    "glass_whisky",
                    "wine_glass_white"
                ]
            },
            "42": {
                "name": "Cooking Set",
                "items": [
                    "cooking_frying_pan_v1",
                    "cooking_frying_pan_v2",
                    "cooking_frying_pan_v3",
                    "cooking_hanging_pans_v1",
                    "cooking_hanging_pans_v2",
                    "cooking_stockpot_v1",
                    "cooking_stockpot_v2",
                    "cooking_stockpot_v3",
                    "cooking_tea_kettle_v1",
                    "cooking_tea_kettle_v2",
                    "cooking_tea_kettle_v3"
                ]
            },
            "43": {
                "name": "Kitchen Set",
                "items": [
                    "champions_kitchen_blue",
                    "champions_kitchen_green",
                    "champions_kitchen_pink",
                    "champions_kitchen_yellow",
                    "kitchen_garlic_braid",
                    "kitchen_hanging_onion_basket",
                    "kitchen_herb_planter_v1",
                    "kitchen_herb_planter_v2",
                    "kitchen_scale_blue",
                    "kitchen_scale_orange",
                    "kitchen_scale_pink",
                    "kitchen_scale_yellow",
                    "kitchen_mixing_bowls_v1",
                    "kitchen_mixing_bowls_v2",
                    "kitchen_mixing_bowls_v3",
                    "kitchen_mixing_bowls_v4",
                    "kitchen_oil_and_vinegar_basket_v1",
                    "kitchen_oil_and_vinegar_basket_v2",
                    "kitchen_salt_and_pepper_shakers",
                    "kitchen_utensil_holder_blue",
                    "kitchen_utensil_holder_green",
                    "kitchen_utensil_holder_pink",
                    "kitchen_utensil_holder_white"
                ]
            },
            "44": {
                "name": "Craft Set",
                "items": [
                    "craft_rug_v1",
                    "craft_rug_v2",
                    "craft_rug_v3",
                    "craft_fabric_rack_v1",
                    "craft_fabric_rack_v2",
                    "craft_fabric_rack_v3",
                    "craft_closed_sewing_tin_v1",
                    "craft_closed_sewing_tin_v2",
                    "craft_closed_sewing_tin_v3",
                    "craft_open_sewing_tin_v1",
                    "craft_open_sewing_tin_v2",
                    "craft_open_sewing_tin_v3",
                    "craft_yarn_basket_v1",
                    "craft_yarn_basket_v2",
                    "craft_yarn_basket_v3"
                ]
            },
            "45": {
                "name": "Cottage Garden Set",
                "items": [
                    "cottage_garden_arch_v1",
                    "cottage_garden_arch_v2",
                    "cottage_garden_planter_v1",
                    "cottage_garden_planter_v2",
                    "cottage_garden_planter_v3",
                    "cottage_garden_shed_v1",
                    "cottage_garden_shed_v2",
                    "cottage_garden_trellis_v1",
                    "cottage_garden_trellis_v2",
                    "cottage_garden_trellis_v3",
                    "cottage_garden_workbench_v1",
                    "cottage_garden_workbench_v2"
                ]
            },
            "46": {
                "name": "Bathroom Set",
                "items": [
                    "bathroom_bench_black",
                    "bathroom_bench_white",
                    "bathroom_curtain_stand_black",
                    "bathroom_curtain_stand_blue",
                    "bathroom_curtain_stand_brown",
                    "bathroom_curtain_stand_green",
                    "bathroom_curtain_stand_light_green",
                    "bathroom_curtain_stand_pink",
                    "bathroom_curtain_stand_white",
                    "bathroom_floor_mirror_black",
                    "bathroom_floor_mirror_white",
                    "bathroom_sink_black",
                    "bathroom_sink_white",
                    "bathroom_tile_wall_blue",
                    "bathroom_tile_wall_green",
                    "bathroom_tile_wall_light_green",
                    "bathroom_tile_wall_pink",
                    "bathroom_wall_mirror_black",
                    "bathroom_wall_mirror_white",
                    "bathroom_wall_sconce",
                    "bathroom_wall_towel_black",
                    "bathroom_wall_towel_blue",
                    "bathroom_wall_towel_brown",
                    "bathroom_wall_towel_green",
                    "bathroom_wall_towel_light_green",
                    "bathroom_wall_towel_pink",
                    "bathroom_wall_towel_white",
                    "bathtub_black",
                    "bathtub_white",
                    "gold_floor_mirror",
                    "gold_wall_mirror",
                    "herringbone_tile_floor_blue",
                    "herringbone_tile_floor_green",
                    "herringbone_tile_floor_white",
                    "large_fluffy_rug_beige",
                    "large_fluffy_rug_black",
                    "large_fluffy_rug_blue",
                    "large_fluffy_rug_brown",
                    "large_fluffy_rug_green",
                    "large_fluffy_rug_light_green",
                    "large_fluffy_rug_pink",
                    "large_fluffy_rug_white",
                    "round_cushioned_stool_beige",
                    "round_cushioned_stool_black",
                    "round_cushioned_stool_blue",
                    "round_cushioned_stool_brown",
                    "round_cushioned_stool_green",
                    "round_cushioned_stool_light_green",
                    "round_cushioned_stool_pink",
                    "round_cushioned_stool_white",
                    "small_bathmat_beige",
                    "small_bathmat_black",
                    "small_bathmat_blue",
                    "small_bathmat_brown",
                    "small_bathmat_green",
                    "small_bathmat_light_green",
                    "small_bathmat_pink",
                    "small_bathmat_white",
                    "square_tile_floor",
                    "toilet_black",
                    "toilet_white"
                ]
            },
            "47": {
                "name": "Counter Set",
                "items": [
                    "counter_basic_v1",
                    "counter_basic_v2",
                    "counter_cabin_cherry",
                    "counter_cabin_oak",
                    "counter_cabin_walnut",
                    "counter_cake_chocolate",
                    "counter_cake_double_chocolate",
                    "counter_cake_strawberry",
                    "counter_kitchen_blue",
                    "counter_kitchen_green",
                    "counter_kitchen_pink",
                    "counter_kitchen_yellow",
                    "counter_cottage_v1",
                    "counter_cottage_v2"
                ]
            },
            "48": {
                "name": "Paving Stone Set",
                "items": [
                    "color_paving_stone_v01",
                    "color_paving_stone_v02",
                    "color_paving_stone_v03",
                    "color_paving_stone_v04",
                    "color_paving_stone_v05",
                    "color_paving_stone_v06",
                    "color_paving_stone_v07",
                    "color_paving_stone_v08",
                    "color_paving_stone_v09",
                    "color_paving_stone_v10",
                    "color_paving_stone_v11",
                    "color_paving_stone_v12",
                    "color_paving_stone_v13",
                    "color_paving_stone_v14",
                    "color_paving_stone_v15",
                    "color_paving_stone_v16",
                    "color_paving_stone_v17",
                    "color_paving_stone_v18",
                    "color_paving_stone_v19",
                    "color_paving_stone_v20",
                    "color_paving_stone_v21",
                    "color_paving_stone_v22",
                    "color_paving_stone_v23",
                    "color_paving_stone_v24",
                    "color_paving_stone_v25",
                    "color_paving_stone_v26",
                    "color_paving_stone_v27",
                    "color_paving_stone_v28",
                    "color_paving_stone_v29",
                    "color_paving_stone_v30",
                    "color_paving_stone_v31",
                    "color_paving_stone_v32",
                    "color_paving_stone_v33",
                    "color_paving_stone_v34",
                    "color_paving_stone_v35",
                    "color_paving_stone_v36",
                    "color_paving_stone_v37",
                    "color_paving_stone_v38",
                    "color_paving_stone_v39",
                    "color_paving_stone_v40",
                    "color_paving_stone_v41",
                    "color_paving_stone_v42"
                ]
            }
        },
        "img": "basic_bed_double_oak"
    },
    "cooking": {
        "name": "Cooking",
        "subcategories": {
            "0": {
                "name": "Pantry",
                "items": [
                    "blackberry_jam",
                    "blueberry_jam",
                    "marmalade",
                    "rosehip_jam",
                    "wild_berry_jam",
                    "bread",
                    "noodles"
                ]
            },
            "1": {
                "name": "Snacks",
                "items": [
                    "berry_bowl",
                    "canned_sardines",
                    "crispy_fried_earthshroom",
                    "crunchy_chickpeas",
                    "deviled_eggs",
                    "dried_squid",
                    "hard_boiled_egg",
                    "pineshroom_toast",
                    "roasted_chestnuts",
                    "spicy_cheddar_biscuit",
                    "spicy_water_chestnuts",
                    "toasted_sunflower_seeds",
                    "trail_mix",
                    "water_chestnut_fritters"
                ]
            },
            "2": {
                "name": "Salads & Greens",
                "items": [
                    "beet_salad",
                    "broccoli_salad",
                    "cabbage_slaw",
                    "cucumber_salad",
                    "herb_salad",
                    "seaweed_salad",
                    "spring_salad",
                    "summer_salad",
                    "tide_salad",
                    "turnip_and_cabbage_salad",
                    "braised_carrots",
                    "buttered_peas",
                    "grilled_corn",
                    "sauteed_snow_peas",
                    "sesame_broccoli",
                    "sliced_turnip",
                    "steamed_broccoli"
                ]
            },
            "3": {
                "name": "Soups & Stews",
                "items": [
                    "beet_soup",
                    "clam_chowder",
                    "deep_sea_soup",
                    "gazpacho",
                    "onion_soup",
                    "potato_soup",
                    "pumpkin_stew",
                    "smoked_trout_soup",
                    "tomato_soup",
                    "vegetable_soup",
                    "fish_stew",
                    "miners_mushroom_stew",
                    "winter_stew"
                ]
            },
            "4": {
                "name": "Main Courses",
                "items": [
                    "cucumber_sandwich",
                    "fish_tacos",
                    "jam_sandwich",
                    "lobster_roll",
                    "mackerel_sashimi",
                    "red_snapper_sushi",
                    "riceball",
                    "salmon_sashimi",
                    "sesame_tuna_bowl",
                    "spicy_crab_sushi",
                    "sushi_platter",
                    "tuna_sashimi",
                    "veggie_sub_sandwich",
                    "fish_skewer",
                    "grilled_cheese",
                    "grilled_eel_rice_bowl",
                    "spicy_corn",
                    "fried_rice",
                    "mushroom_steak_dinner",
                    "perch_risotto",
                    "sea_bream_rice",
                    "seafood_snow_pea_noodles",
                    "vegetable_pot_pie",
                    "breaded_catfish",
                    "horseradish_salmon",
                    "omelet",
                    "pan_fried_bream",
                    "pan_fried_salmon",
                    "pan_fried_snapper",
                    "spicy_corn",
                    "baked_potato",
                    "baked_sweetroot",
                    "cod_with_thyme",
                    "garlic_bread",
                    "harvest_plate",
                    "loaded_baked_potato",
                    "pizza",
                    "quiche",
                    "spring_galette",
                    "turnip_and_potato_gratin",
                    "vegetable_quiche",
                    "roasted_cauliflower",
                    "roasted_sweet_potato",
                    "seafood_boil",
                    "apple_honey_curry",
                    "braised_burdock",
                    "cauliflower_curry",
                    "chickpea_curry",
                    "chili_coconut_curry",
                    "crab_cakes",
                    "crayfish_etouffee",
                    "deluxe_curry",
                    "herb_butter_pasta",
                    "incredibly_hot_pot",
                    "monster_mash",
                    "mushroom_rice",
                    "rosemary_garlic_noodles",
                    "simmered_daikon"
                ]
            },
            "5": {
                "name": "Desserts",
                "items": [
                    "berries_and_cream",
                    "peaches_and_cream",
                    "salted_watermelon",
                    "strawberries_and_cream",
                    "apple_pie",
                    "bell_berry_bakewell_tart",
                    "caldosian_chocolate_cake",
                    "cherry_cobbler",
                    "cherry_tart",
                    "coconut_cream_pie",
                    "cranberry_orange_scone",
                    "crystal_berry_pie",
                    "glowberry_cookies",
                    "golden_cheesecake",
                    "golden_cookies",
                    "lemon_pie",
                    "monster_cookie",
                    "mont_blanc",
                    "moon_fruit_cake",
                    "poached_pear",
                    "pumpkin_pie",
                    "queen_berry_pie",
                    "sour_lemon_cake",
                    "strawberry_shortcake",
                    "sweet_potato_pie",
                    "wildberry_pie",
                    "wildberry_scone",
                    "ice_cream_sundae",
                    "pomegranate_sorbet",
                    "spell_fruit_parfait",
                    "wintergreen_ice_cream",
                    "candied_lemon_peel",
                    "candied_queen_berries",
                    "candied_strawberries",
                    "candied_walnuts",
                    "caramel_candy",
                    "caramelized_moon_fruit",
                    "pudding",
                    "sweet_sesame_balls"
                ]
            },
            "6": {
                "name": "Drinks",
                "items": [
                    "apple_juice",
                    "cherry_smoothie",
                    "coconut_milk",
                    "cranberry_juice",
                    "grape_juice",
                    "iced_coffee",
                    "lemonade",
                    "orange_juice",
                    "pomegranate_juice",
                    "cup_of_tea",
                    "green_tea",
                    "hot_cocoa",
                    "jasmine_tea",
                    "latte",
                    "mocha",
                    "roasted_rice_tea",
                    "rose_tea",
                    "spirit_mushroom_tea"
                ]
            }
        },
        "img": "fish_stew"
    }
}